mobile/urls.py
from django.urls import path
from .views import *
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('', countries, name="countries"),
    path('<slug:slug>/', operators, name='operators' ),
    path('operator/<slug:slug>/', operator_detail, name='detail' ),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mobileoperators/urls.py
from django.contrib import admin
from django.urls import path, include
from mobile.views import countries, welcome
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('network/',include(('mobile.urls', 'mobile'), namespace='country')),
    path('', welcome, name="welcome"),
    
     
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mobile/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.
class Countries(models.Model):
    country_name = models.CharField(max_length=100)
    country_flag = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, max_length=100)
    
    def __str__(self):
        return self.country_name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.country_name)
        return super(Countries, self).save(*args, **kwargs)      

class Operators(models.Model):

    operator_name = models.CharField(max_length=100)
    operator_description = models.TextField(blank=True)
    image = models.FileField(null=True, blank=True )
    slug = models.SlugField(unique=True, max_length=100)
    country = models.ForeignKey('mobile.Countries', related_name='operators', on_delete=models.CASCADE) 

    def __str__(self):
        return self.operator_name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.operator_name)
        return super(Operators, self).save(*args, **kwargs)    

mobile/forms.py
from django import forms
from .models import *

class OperatorForm(forms.ModelForm):
    class Meta:
         model=Operators

         fields = [
             'country'
             'operator_name',
             'operator_description',
             'image'
         ]

mobile/views.py
from django.shortcuts import render,get_object_or_404,HttpResponseRedirect,get_list_or_404
from .models import *
from django.utils.text import slugify
# Create your views here.



def operator_detail(request, slug):
    detail = get_object_or_404(Operators, slug=slug)
    context={
        'detail':detail,
        
    }
    template="operator_detail.html"
    return render(request, template, context)

def operators(request, slug):
    country = get_object_or_404(Countries, slug=slug)
    operators = Operators.objects.filter(slug=slug)
    context = {
     
        'country':country,
        'operators':operators,
    }
    template="operators.html"
    return render(request, template, context)

def countries(request):
    countries = Countries.objects.all()
    context = {
        'countries':countries,
    }
    template = "country.html"
    return render(request, template, context)

def welcome(request):
    template = "welcome.html"
    return render(request, template )                      

templates/country.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Country</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="Afghanistan,Albania,Algeria,Andorra,Angola,Antigua and Barbuda,Argentina,Armenia, Aruba,Australia, Austria,Azerbaijan">
    <meta name="keywords" content="Bangladesh,Barbados,Belarus,Belgium, Belize, Benin,Bhutan,Bolivia,Bosnia and Herzegovina,Botswana,Brazil,Brunei,Bulgaria,Burkina Faso,Burma,Burundi">
    <meta name="keywords" content="Cambodia,Cameroon,Canada,Cabo Verde,Central African Republic,Chad,Chile,China,Colombia,Comoros,Congo, Democratic Republic of the,Congo, Republic of the,Costa Rica,Cote d'Ivoire,Croatia,Cuba,Curacao, Cyprus,Czechia,">
    <meta name="keywords" content="Denmark,Djibouti,Dominica,Dominican Republic">
    <meta name="keywords" content="Ecuador,Egypt,El Salvador,Equatorial Guinea,Eritrea,Estonia,Eswatini,Ethiopia">
    <meta name="keywords" content=" Fiji,Finland,France">
    <meta name="keywords" content="Gabon,Georgia,Germany,Ghana,Greece,Grenada,Guatemala,Guinea,Guinea-Bissau,Guyana">
    <meta name="keywords" content="Haiti,Holy See,Honduras,Hong Kong,Hungary">
    <meta name="keywords" content="Iceland,India,Indonesia,Iran,Iraq,Ireland,Israel,Italy">
    <meta name="keywords" content="Jamaica,Japan,Jordan">
    <meta name="keywords" content="Kazakhstan,Kenya,Kiribati,Korea, North,Korea, South,Kosovo,Kuwait,Kyrgyzstan">
    <meta name="keywords" content=" Laos, Latvia, Lebanon, Lesotho, Liberia, Libya, Liechtenstein, Lithuania, Luxembourg">
    <meta name="keywords" content="  Macau,Macedonia,Madagascar,Malawi,Malaysia,Maldives,Mali,Malta,Marshall Islands,Mauritania,Mauritius,Mexico,Micronesia,Moldova,Monaco,Mongolia,Montenegro,Morocco,Mozambique">
    <meta name="keywords" content="Namibia,Nauru,Nepal,Netherlands,New Zealand,Nicaragua,Niger,Nigeria,North Korea,Norway">
    <meta name="keywords" content=" Pakistan, Palau, Palestinian Territories, Panama, Papua New Guinea, Paraguay, Peru, Philippines, Poland, Portugal">
    <meta name="keywords" content="Qatar,Romania,Russia,Rwanda">
    <meta name="keywords" content=" Saint Kitts and Nevis, Saint Lucia, Saint Vincent and the Grenadines, Samoa, San Marino, Sao Tome and Principe, Saudi Arabia, Senegal, Serbia, Seychelles">
    <meta name="keywords" content="Sierra Leone,Singapore,Sint Maarten,Slovakia,Slovenia,Solomon Islands,Somalia,South Africa,South Korea,South Sudan,Spain,Sri Lanka,Sudan,Suriname,Swaziland,Sweden,Switzerland,Syria">
    <meta name="keywords" content="Taiwan,Tajikistan,Tanzania,Thailand,Timor-Leste,Togo,Tonga,Trinidad and Tobago,Tunisia,Turkey,Turkmenistan,Tuvalu">
    <meta name="keywords" content="Uganda,Ukraine,United Arab Emirates,United Kingdom,Uruguay,Uzbekistan,Vanuatu,Venezuela,Vietnam">
    <meta name="description" content="FindMobiNet provides you information about mobile networks from different countries. Connect your country and get info... ">
    <link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet"> 
    <link rel="stylesheet" type="text/css"  href="/static/css/design.css" />
    <link rel="stylesheet" type="text/css"  href="/static/css/flag-icon-css/css/flag-icon.min.css" />
    
    

</head>
<body>

<div class="container-scifi">
        <h5>which country would you like to connect ...</h5>
    </div>
    <div class="container-scifi"></div>
    

</div>
    <div class="background">
        <div class="container-country">
                {% for country in countries %}
                <a href="{% url 'country:operators' country.slug %}" class="button" style="text-decoration: none;"><span class="flag-icon flag-icon-{{country.country_flag}}"></span> {{ country.country_name }}</a>
                {% endfor %}
              </div>
            </div>  
  






           <script src="/static/js/scifi.js"></script>
</body>
</html>

templates/operator_detail.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{detail.operator_name}}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="Afghanistan,Albania,Algeria,Andorra,Angola,Antigua and Barbuda,Argentina,Armenia, Aruba,Australia, Austria,Azerbaijan">
    <meta name="keywords" content="Bangladesh,Barbados,Belarus,Belgium, Belize, Benin,Bhutan,Bolivia,Bosnia and Herzegovina,Botswana,Brazil,Brunei,Bulgaria,Burkina Faso,Burma,Burundi">
    <meta name="keywords" content="Cambodia,Cameroon,Canada,Cabo Verde,Central African Republic,Chad,Chile,China,Colombia,Comoros,Congo, Democratic Republic of the,Congo, Republic of the,Costa Rica,Cote d'Ivoire,Croatia,Cuba,Curacao, Cyprus,Czechia,">
    <meta name="keywords" content="Denmark,Djibouti,Dominica,Dominican Republic">
    <meta name="keywords" content="Ecuador,Egypt,El Salvador,Equatorial Guinea,Eritrea,Estonia,Eswatini,Ethiopia">
    <meta name="keywords" content=" Fiji,Finland,France">
    <meta name="keywords" content="Gabon,Georgia,Germany,Ghana,Greece,Grenada,Guatemala,Guinea,Guinea-Bissau,Guyana">
    <meta name="keywords" content="Haiti,Holy See,Honduras,Hong Kong,Hungary">
    <meta name="keywords" content="Iceland,India,Indonesia,Iran,Iraq,Ireland,Israel,Italy">
    <meta name="keywords" content="Jamaica,Japan,Jordan">
    <meta name="keywords" content="Kazakhstan,Kenya,Kiribati,Korea, North,Korea, South,Kosovo,Kuwait,Kyrgyzstan">
    <meta name="keywords" content=" Laos, Latvia, Lebanon, Lesotho, Liberia, Libya, Liechtenstein, Lithuania, Luxembourg">
    <meta name="keywords" content="  Macau,Macedonia,Madagascar,Malawi,Malaysia,Maldives,Mali,Malta,Marshall Islands,Mauritania,Mauritius,Mexico,Micronesia,Moldova,Monaco,Mongolia,Montenegro,Morocco,Mozambique">
    <meta name="keywords" content="Namibia,Nauru,Nepal,Netherlands,New Zealand,Nicaragua,Niger,Nigeria,North Korea,Norway">
    <meta name="keywords" content=" Pakistan, Palau, Palestinian Territories, Panama, Papua New Guinea, Paraguay, Peru, Philippines, Poland, Portugal">
    <meta name="keywords" content="Qatar,Romania,Russia,Rwanda">
    <meta name="keywords" content=" Saint Kitts and Nevis, Saint Lucia, Saint Vincent and the Grenadines, Samoa, San Marino, Sao Tome and Principe, Saudi Arabia, Senegal, Serbia, Seychelles">
    <meta name="keywords" content="Sierra Leone,Singapore,Sint Maarten,Slovakia,Slovenia,Solomon Islands,Somalia,South Africa,South Korea,South Sudan,Spain,Sri Lanka,Sudan,Suriname,Swaziland,Sweden,Switzerland,Syria">
    <meta name="keywords" content="Taiwan,Tajikistan,Tanzania,Thailand,Timor-Leste,Togo,Tonga,Trinidad and Tobago,Tunisia,Turkey,Turkmenistan,Tuvalu">
    <meta name="keywords" content="Uganda,Ukraine,United Arab Emirates,United Kingdom,Uruguay,Uzbekistan,Vanuatu,Venezuela,Vietnam">
    <meta name="keywords" content="{{detail.operator_name}}">
    <meta name="description" content="FindMobiNet provides you information about mobile networks from different countries. Connect your country and get info... ">
    <meta name="description" content="Services for operator {{detail.operator_name}}.">

    <link rel="stylesheet" type="text/css"  href="/static/css/detail.css" />
    <link rel="stylesheet" type="text/css"  href="/static/css/bootstrap.min.css" />

    
</head>
<body>
       
              
                        <div class="container py-5">
                          
                              
                            <div class="row">
                                <div class="card scifi-pic col-md-4">
                                  
                                        <div class="card-block py-4  ">
                                            <div class="container">
                                                <img class="img-fluid " src="/media/{{detail.image}}" alt="">
                                            </div>
                                        </div>
                                           
                                </div>

                                    <div class="col-md-1 py-2"></div>

                                   <div class="card scifi col-md-7">
                                
                                    <div class="container">
                                  <div class="card-block py-4">
                                   
                                        <p class="card-text scifi-text">{{detail.operator_description|linebreaks}}</p>
                                        
                                        
              
                                  </div>
                                
                                </div>
                      
                              </div>
                            </div>
                          </div>
                        </div>
                     
              
</body>

</html>

templates/operators.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{country.country_name}}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="Afghanistan,Albania,Algeria,Andorra,Angola,Antigua and Barbuda,Argentina,Armenia, Aruba,Australia, Austria,Azerbaijan">
    <meta name="keywords" content="Bangladesh,Barbados,Belarus,Belgium, Belize, Benin,Bhutan,Bolivia,Bosnia and Herzegovina,Botswana,Brazil,Brunei,Bulgaria,Burkina Faso,Burma,Burundi">
    <meta name="keywords" content="Cambodia,Cameroon,Canada,Cabo Verde,Central African Republic,Chad,Chile,China,Colombia,Comoros,Congo, Democratic Republic of the,Congo, Republic of the,Costa Rica,Cote d'Ivoire,Croatia,Cuba,Curacao, Cyprus,Czechia,">
    <meta name="keywords" content="Denmark,Djibouti,Dominica,Dominican Republic">
    <meta name="keywords" content="Ecuador,Egypt,El Salvador,Equatorial Guinea,Eritrea,Estonia,Eswatini,Ethiopia">
    <meta name="keywords" content=" Fiji,Finland,France">
    <meta name="keywords" content="Gabon,Georgia,Germany,Ghana,Greece,Grenada,Guatemala,Guinea,Guinea-Bissau,Guyana">
    <meta name="keywords" content="Haiti,Holy See,Honduras,Hong Kong,Hungary">
    <meta name="keywords" content="Iceland,India,Indonesia,Iran,Iraq,Ireland,Israel,Italy">
    <meta name="keywords" content="Jamaica,Japan,Jordan">
    <meta name="keywords" content="Kazakhstan,Kenya,Kiribati,Korea, North,Korea, South,Kosovo,Kuwait,Kyrgyzstan">
    <meta name="keywords" content=" Laos, Latvia, Lebanon, Lesotho, Liberia, Libya, Liechtenstein, Lithuania, Luxembourg">
    <meta name="keywords" content="  Macau,Macedonia,Madagascar,Malawi,Malaysia,Maldives,Mali,Malta,Marshall Islands,Mauritania,Mauritius,Mexico,Micronesia,Moldova,Monaco,Mongolia,Montenegro,Morocco,Mozambique">
    <meta name="keywords" content="Namibia,Nauru,Nepal,Netherlands,New Zealand,Nicaragua,Niger,Nigeria,North Korea,Norway">
    <meta name="keywords" content=" Pakistan, Palau, Palestinian Territories, Panama, Papua New Guinea, Paraguay, Peru, Philippines, Poland, Portugal">
    <meta name="keywords" content="Qatar,Romania,Russia,Rwanda">
    <meta name="keywords" content=" Saint Kitts and Nevis, Saint Lucia, Saint Vincent and the Grenadines, Samoa, San Marino, Sao Tome and Principe, Saudi Arabia, Senegal, Serbia, Seychelles">
    <meta name="keywords" content="Sierra Leone,Singapore,Sint Maarten,Slovakia,Slovenia,Solomon Islands,Somalia,South Africa,South Korea,South Sudan,Spain,Sri Lanka,Sudan,Suriname,Swaziland,Sweden,Switzerland,Syria">
    <meta name="keywords" content="Taiwan,Tajikistan,Tanzania,Thailand,Timor-Leste,Togo,Tonga,Trinidad and Tobago,Tunisia,Turkey,Turkmenistan,Tuvalu">
    <meta name="keywords" content="Uganda,Ukraine,United Arab Emirates,United Kingdom,Uruguay,Uzbekistan,Vanuatu,Venezuela,Vietnam">
    <meta name="description" content="FindMobiNet provides you information about mobile networks from different countries. Connect your country and get info... ">
    

    <link rel="stylesheet" type="text/css"  href="/static/css/design.css" />
    <link href="http://allfont.net/allfont.css?fonts=orbitron-black" rel="stylesheet" type="text/css" />
    

</head>
<body>
        <div class="container-scifi">
                <h5>which operator would you like to connect ...</h5>
        </div>
                
                <div class="container-scifi"></div>
        
    <div class="background">
        <div class="container-country">
                {% for oper in country.operators.all %}
                <a href="/network/operator/{{oper.slug}}/" class="button" style="text-decoration: none;">{{oper.operator_name}}</a>
                {% endfor %}
              </div>
            </div>  
  




        <script src="/static/js/scifi.js"></script>


</body>
</html>

templates/test.html
test

templates/welcome.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>SpiderNet</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css"  href="/static/css/welcome.css" />
  
    

</head>
<body>
      <div id="loading" class="loader">
            <div class="loader__figure"></div>
            <p class="loader__label">Connecting...</p>
          </div>
      
        <div class="container demo">
                <div class="content">
                   <div id="large-header" class="large-header">
                      <canvas id="demo-canvas"></canvas>
                      <h1 class="main-title"><span class="thin">Spider</span>Net</h1>
                      <h4 class="second-title"><span class="thin">mobile networks</span></h4>
                      <div class="flex-grid-center">
                          <a class="pure-button fuller-button blue" href="{% url 'country:countries'%}">CONNECT</a>
                         </div>
                   </div>
                </div>
             </div>
      
               

         
           
<script src="/static/js/jquery.min.js" ></script>
<script src="/static/js/net.js"></script>
<script type="text/javascript">
   $(window).load(function() {
   $('#loading').hide();
});
</script>
</body>
</html>